"""
VoltAI Stage 12 — Real-Time Telemetry Streaming API

Provides a WebSocket endpoint that streams simulated smart-meter readings
to connected dashboard clients. Readings are generated by the telemetry
simulator and sent at 1-second intervals.

Design decisions:
    - WebSocket (not SSE) for full-duplex potential and broad browser support.
    - Graceful disconnect handling: catches WebSocketDisconnect and asyncio.CancelledError.
    - Per-connection interval: each client gets its own stream; server-side state
      (battery SoC) is shared across all connections for the same site_id.
    - Interval is configurable via query param ?interval_ms=1000 (default 1000ms,
      min 500ms, max 5000ms) for demo flexibility without code changes.
"""

import asyncio
import json
import logging

from fastapi import APIRouter, Query, WebSocket, WebSocketDisconnect

from backend.app.services.telemetry_simulator import simulate_reading

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/telemetry", tags=["Real-Time Telemetry"])


@router.websocket("/stream/{site_id}")
async def telemetry_stream(
    websocket: WebSocket,
    site_id: str,
    interval_ms: int = Query(default=1000, ge=500, le=5000, description="Streaming interval in milliseconds"),
):
    """
    WebSocket endpoint — streams live simulated smart-meter telemetry.

    Connect: ws://host:8000/api/v1/telemetry/stream/{site_id}?interval_ms=1000

    Message format (JSON):
        {
          "type": "telemetry",
          "timestamp": "<ISO-8601 UTC>",
          "site_id": "<site>",
          "solar_generation_kw": 45.2,
          "wind_generation_kw": 18.7,
          "energy_consumption_kw": 63.1,
          "battery_soc_pct": 72.4,
          "battery_charge_kw": 0.0,
          "battery_discharge_kw": 4.3,
          "grid_import_kw": 0.0,
          "grid_export_kw": 0.8,
          "renewable_fraction_pct": 84.6
        }

    Disconnect: close the WebSocket from the client side.
    """
    await websocket.accept()
    logger.info("WebSocket connected: site_id=%s interval_ms=%d", site_id, interval_ms)

    interval_s = interval_ms / 1000.0

    try:
        while True:
            reading = simulate_reading(site_id, interval_seconds=interval_s)
            await websocket.send_text(json.dumps(reading))
            await asyncio.sleep(interval_s)

    except WebSocketDisconnect:
        logger.info("WebSocket disconnected cleanly: site_id=%s", site_id)
    except asyncio.CancelledError:
        logger.info("WebSocket task cancelled: site_id=%s", site_id)
    except Exception as exc:
        logger.warning("WebSocket stream error: site_id=%s error=%s", site_id, exc)
    finally:
        try:
            await websocket.close()
        except Exception:
            pass
