"""
VoltAI Feature Engineering Service

Extracts time-series features for energy telemetry without target leakage.
Supports time, cyclical, lag, rolling, and state features.
"""

from typing import List, Tuple
import numpy as np
import pandas as pd

MIN_COLD_START_HOURS = 168  # 168 hours history needed for t-168 lag


class FeatureEngineeringService:
    """
    Feature engineering transformer for VoltAI forecasting models.
    Operates strictly on data for a single site to ensure site isolation.
    """

    @staticmethod
    def prepare_dataframe(readings_df: pd.DataFrame) -> pd.DataFrame:
        """
        Sort and set index for energy readings dataframe.
        Must contain 'timestamp' and target columns.
        """
        df = readings_df.copy()
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"])
            df = df.sort_values("timestamp").reset_index(drop=True)
        return df

    @staticmethod
    def create_features(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
        """
        Engineers features for a given target column ('solar_generation', 'wind_generation', or 'energy_consumption').
        
        Strict Leakage Protection:
        Features at index t are computed exclusively using rows <= t.
        """
        df = df.copy()
        target_series = df[target_col].astype(float)

        # 1. Time & Cyclical features (derived from timestamp at time t)
        timestamps = pd.to_datetime(df["timestamp"])
        hour = timestamps.dt.hour
        day_of_week = timestamps.dt.dayofweek

        df["hour_of_day"] = hour
        df["day_of_week"] = day_of_week
        df["is_weekend"] = day_of_week.isin([5, 6]).astype(int)

        # Cyclical transformations
        df["hour_sin"] = np.sin(2 * np.pi * hour / 24.0)
        df["hour_cos"] = np.cos(2 * np.pi * hour / 24.0)
        df["day_of_week_sin"] = np.sin(2 * np.pi * day_of_week / 7.0)
        df["day_of_week_cos"] = np.cos(2 * np.pi * day_of_week / 7.0)

        # 2. Lag features (strictly shift >= 1)
        df["lag_1"] = target_series.shift(1)
        df["lag_2"] = target_series.shift(2)
        df["lag_3"] = target_series.shift(3)
        df["lag_24"] = target_series.shift(24)
        df["lag_48"] = target_series.shift(48)
        df["lag_168"] = target_series.shift(168)

        # 3. Rolling window features (using shift(1) to prevent leakage of target_t)
        shifted_target = target_series.shift(1)

        df["rolling_mean_6"] = shifted_target.rolling(window=6, min_periods=1).mean()
        df["rolling_std_6"] = shifted_target.rolling(window=6, min_periods=2).std().fillna(0.0)
        df["rolling_mean_24"] = shifted_target.rolling(window=24, min_periods=1).mean()
        df["rolling_min_24"] = shifted_target.rolling(window=24, min_periods=1).min()
        df["rolling_max_24"] = shifted_target.rolling(window=24, min_periods=1).max()

        # Exponential Moving Averages (EMA)
        df["ema_6"] = shifted_target.ewm(span=6, adjust=False).mean()
        df["ema_24"] = shifted_target.ewm(span=24, adjust=False).mean()

        # 4. State feature
        if "battery_soc" in df.columns:
            df["recent_battery_soc"] = df["battery_soc"].shift(1).fillna(50.0)
        else:
            df["recent_battery_soc"] = 50.0

        return df

    @classmethod
    def get_feature_column_names(cls) -> List[str]:
        """
        Return the list of feature column names generated by create_features.
        """
        return [
            "hour_of_day",
            "day_of_week",
            "is_weekend",
            "hour_sin",
            "hour_cos",
            "day_of_week_sin",
            "day_of_week_cos",
            "lag_1",
            "lag_2",
            "lag_3",
            "lag_24",
            "lag_48",
            "lag_168",
            "rolling_mean_6",
            "rolling_std_6",
            "rolling_mean_24",
            "rolling_min_24",
            "rolling_max_24",
            "ema_6",
            "ema_24",
            "recent_battery_soc",
        ]

    @classmethod
    def create_training_dataset(
        cls, df: pd.DataFrame, target_col: str, horizon_steps: int = 24
    ) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        """
        Constructs X (features at time t) and Y (multi-output targets t+1 to t+24).

        Returns:
            (X, Y, clean_df) where X and Y are aligned, with NaNs dropped.
        """
        if len(df) < MIN_COLD_START_HOURS:
            raise ValueError(
                f"Insufficient historical data: {len(df)} rows provided, minimum required is {MIN_COLD_START_HOURS} hours."
            )

        df_feat = cls.create_features(df, target_col)
        feature_cols = cls.get_feature_column_names()

        # Create 24 multi-output target columns [y_t+1, ..., y_t+24]
        target_series = df_feat[target_col].astype(float)
        target_cols = []
        for step in range(1, horizon_steps + 1):
            col_name = f"target_step_{step}"
            df_feat[col_name] = target_series.shift(-step)
            target_cols.append(col_name)

        # Drop rows where features or multi-output targets have NaNs (due to lag_168 or shift(-24))
        valid_df = df_feat.dropna(subset=feature_cols + target_cols).reset_index(drop=True)

        X = valid_df[feature_cols]
        Y = valid_df[target_cols]

        return X, Y, valid_df

    @classmethod
    def create_inference_features(cls, df: pd.DataFrame, target_col: str) -> pd.DataFrame:
        """
        Extracts the single feature row at the latest available timestamp (time t) for 24-step forecasting.
        """
        if len(df) < MIN_COLD_START_HOURS:
            raise ValueError(
                f"Insufficient historical data for inference: {len(df)} rows, minimum required is {MIN_COLD_START_HOURS} hours."
            )

        df_feat = cls.create_features(df, target_col)
        feature_cols = cls.get_feature_column_names()
        latest_features = df_feat.iloc[[-1]][feature_cols]
        return latest_features
